name: Node.js CI

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: self-hosted
    if: github.event.pull_request.merged == true

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Create env file
        run: |
          touch .env
          echo JWT_SECRET='${{ secrets.JWT_SECRET }}' >> .env
          echo MONGO_URI='${{ secrets.MONGO_URI }}' >> .env
          echo SERVER_PORT='${{ secrets.SERVER_PORT }}' >> .env
          cat .env
      - run: npm i
      - run: npm run
      - run: pm2 restart 0